### ISSUE TITLE
Roadmap for 2.0.0

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-pointer-events#3]
Progress in branch `convergence`

- [x] Merge elm-mouse-events
- [x] Merge elm-touch-events
- [x] Complete mouse events
- [x] Complete mouse properties
- [x] Improve mouse documentation
- [x] Complete touch events
- [x] Complete touch properties
- [x] Improve touch documentation
- [x] Create a `Wheel` module for corresponding event
- [x] Try to provide features mentionned on [reddit post][reddit-coordination]
  It seems that every feature has been covered except for the "global" follow of an event
  that moves outside of original element. Pointer capture (#4) might fix it ;)
- [x] Try to bring features of other similar packages (except gestures)
    - knknledg/touch-events: (very minimalist) intended at detecting swiping
    - elm-canvas/element-relative-mouse-events: (very minimalist) for relative position
    - zwilias/elm-touch-events: touch gesture recognition: swipe / tap
    - mbr/elm-mouse-events: onContextMenu is a mouse event, however, onPointerLock{Change,Error} and onSelect are not mouse events.
- [x] Create a `Drag` module for corresponding event
- [x] Complete `Pointer` events (see https://developer.mozilla.org/en-US/docs/Web/Events)
- Try a performance evaluation of decoders on high frequency events like `touchmove` (is there a way to do better?) _Keep for version 2.1_
- Evaluate usability of package for a gesture package on top (exploratory elm-touch-gesture and elm-pointer-gesture maybe, before ultimately create an elm-gesture package?) _Keep for version 2.1_
- [x] Publish version 2.0.0 :)

If you (reader) want to contribute, come say hello [on Slack][elm-slack], I'm @mattpiz there.

[reddit-coordination]: https://www.reddit.com/r/elm/comments/7gksya/pointer_mousetouchpointer_events_community/
[elm-slack]: https://elmlang.herokuapp.com
